Repository KijijiCA/react-advertising, pull requests merged in 2021-05, with the labels that each got.

#47 feat: Enable Lazy Loading
  .gitignore
  .prettierrc
  CHANGELOG.md
  LICENSE
  README.md
  package.json
  src/Advertising.js
  src/__snapshots__/Advertising.test.js.snap
  src/components/AdvertisingProvider.js
  src/components/AdvertisingProvider.test.js
  src/components/AdvertisingSlot.js
  src/components/AdvertisingSlot.test.js
  src/components/__snapshots__/AdvertisingProvider.test.js.snap
  src/components/__snapshots__/AdvertisingSlot.test.js.snap
  src/components/utils/AdvertisingConfigPropType.js
  src/components/utils/AdvertisingConfigPropType.test.js
  src/components/utils/AdvertisingSlotConfigPropType.js
  src/components/utils/AdvertisingSlotConfigPropType.test.js
  src/components/utils/calculateRootMargin.js
  src/components/utils/calculateRootMargin.test.js
  src/components/utils/connectToAdServer.js
  src/components/utils/connectToAdServer.test.js
  src/components/utils/getLazyLoadConfig.js
  src/components/utils/getLazyLoadConfig.test.js
  src/components/utils/isLazyLoading.js
  src/components/utils/isLazyLoading.test.js
  src/components/utils/isMobileDevice.js
  src/components/utils/isMobileDevice.test.js
  src/utils/index.js
  yarn.lock
Labels: feat

#55 chore: Migrate to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: chore

#54 test: End-to-end tests with Storybook and Cypress
  .eslintrc
  .github/workflows/ci.yml
  .gitignore
  .npmignore
  .nycrc
  .storybook/main.js
  .storybook/preview.js
  CHANGELOG.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/gptBanner_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  scripts/checkCoverage.js
  scripts/coverage.config.default.json
  scripts/utils/findReportFiles.js
  scripts/utils/getConfig.js
  scripts/utils/index.js
  src/stories/GptBanner.stories.js
  yarn.lock
Labels: test

#60 test: E2E test for lazy loading
  .gitignore
  .npmignore
  babel.config.js
  cypress.json
  cypress/integration/gptBanner_spec.js
  cypress/integration/gptLazyLoading_spec.js
  cypress/support/commands.js
  package.json
  scripts/checkCoverage.js
  src/stories/GptBanner.stories.js
  src/stories/GptLazyLoading.stories.js
  src/stories/utils/GptDecorator.js
  src/stories/utils/RowLayout.js
  src/stories/utils/Spacer.js
  src/stories/utils/index.js
Labels: test

#62 fix: set advertising queue array
  src/Advertising.js
Labels: fix
